name: Docker Compose CI Test
on:
  pull_request:
    # branches:
    #   - master
    types: [ labeled ]
    paths:
      - '**docker-compose.yaml'

jobs:
  Docker-Compose-Test:
    if: github.event.label.name == 'docker-compose'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup Python3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.7
    - name: Conda install RDKit
      shell: bash -l {0}
      run: |
        conda info
        conda install -c rdkit rdkit -y
    - name: Insatll libsndfile
      run: sudo apt-get install -y libsndfile1
    - name: Insatll ffmpeg
      run: sudo apt-get install -y ffmpeg
    - name: Install pip packeages
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install gdown

    - name: Get all added and modified files as CSV
      id: files
      uses: Ana06/get-changed-files@v2.0.0
      with:
        format: 'csv'
    - name: Run test with docker-compose
      run: |
        mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
        for added_modified_file in "${added_modified_files[@]}"; do
          echo all ${added_modified_file}
          if [[ ${added_modified_file} = *docker-compose.yaml ]]; then
            echo if ${added_modified_file}
            echo cd `dirname ${added_modified_file}`
            cd `dirname ${added_modified_file}`
            python -m pytest test_docker_compose.py
          fi
        done
            
    